# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/izman/.local/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/izman/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/data/projects/aes-bridge/aes-bridge-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/data/projects/aes-bridge/aes-bridge-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/izman/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/izman/.local/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/data/projects/aes-bridge/aes-bridge-cpp/CMakeFiles /home/data/projects/aes-bridge/aes-bridge-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/data/projects/aes-bridge/aes-bridge-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aes_bridge_app

# Build rule for target.
aes_bridge_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aes_bridge_app
.PHONY : aes_bridge_app

# fast build rule for target.
aes_bridge_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/build
.PHONY : aes_bridge_app/fast

src/cbc.o: src/cbc.cpp.o
.PHONY : src/cbc.o

# target to build an object file
src/cbc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/src/cbc.cpp.o
.PHONY : src/cbc.cpp.o

src/cbc.i: src/cbc.cpp.i
.PHONY : src/cbc.i

# target to preprocess a source file
src/cbc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/src/cbc.cpp.i
.PHONY : src/cbc.cpp.i

src/cbc.s: src/cbc.cpp.s
.PHONY : src/cbc.s

# target to generate assembly for a file
src/cbc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/src/cbc.cpp.s
.PHONY : src/cbc.cpp.s

src/common.o: src/common.cpp.o
.PHONY : src/common.o

# target to build an object file
src/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/src/common.cpp.o
.PHONY : src/common.cpp.o

src/common.i: src/common.cpp.i
.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s
.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/gcm.o: src/gcm.cpp.o
.PHONY : src/gcm.o

# target to build an object file
src/gcm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/src/gcm.cpp.o
.PHONY : src/gcm.cpp.o

src/gcm.i: src/gcm.cpp.i
.PHONY : src/gcm.i

# target to preprocess a source file
src/gcm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/src/gcm.cpp.i
.PHONY : src/gcm.cpp.i

src/gcm.s: src/gcm.cpp.s
.PHONY : src/gcm.s

# target to generate assembly for a file
src/gcm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/src/gcm.cpp.s
.PHONY : src/gcm.cpp.s

src/legacy.o: src/legacy.cpp.o
.PHONY : src/legacy.o

# target to build an object file
src/legacy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/src/legacy.cpp.o
.PHONY : src/legacy.cpp.o

src/legacy.i: src/legacy.cpp.i
.PHONY : src/legacy.i

# target to preprocess a source file
src/legacy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/src/legacy.cpp.i
.PHONY : src/legacy.cpp.i

src/legacy.s: src/legacy.cpp.s
.PHONY : src/legacy.s

# target to generate assembly for a file
src/legacy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/src/legacy.cpp.s
.PHONY : src/legacy.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aes_bridge_app.dir/build.make CMakeFiles/aes_bridge_app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... aes_bridge_app"
	@echo "... src/cbc.o"
	@echo "... src/cbc.i"
	@echo "... src/cbc.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/gcm.o"
	@echo "... src/gcm.i"
	@echo "... src/gcm.s"
	@echo "... src/legacy.o"
	@echo "... src/legacy.i"
	@echo "... src/legacy.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

