name: Tests on Linux

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Disable man-db auto-update and reconfigure
      run: |
        echo "set man-db/auto-update false" | sudo debconf-communicate
        sudo dpkg-reconfigure man-db
        sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc > /dev/null << 'EOF'
        path-exclude /usr/share/doc/*
        path-exclude /usr/share/man/*
        path-exclude /usr/share/info/*
        EOF

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt install -y libgtest-dev
        sudo apt install -y nlohmann-json3-dev

    - name: Build Google Test
      run: |
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo mv lib/libgtest* /usr/local/lib/
        sudo mv googletest/include/gtest /usr/local/include/

    - name: Build tests
      run: |
        cmake . -DBUILD_AESBRIDGE_TESTS=ON
        make

    - name: Run tests
      run: |
        ctest --verbose
