name: Tests on Windows

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install ninja
        choco install vcpkg

    - name: Setup vcpkg
      run: |
        $vcpkgRoot = "C:\vcpkg"
        & "$vcpkgRoot\vcpkg.exe" integrate install
        & "$vcpkgRoot\vcpkg.exe" install gtest nlohmann-json

    - name: Build tests
      run: |
        cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake .
        cmake --build .

    - name: Run tests
      run: |
        ctest --verbose
