name: Tests on Windows

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install ninja

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
        cd C:\vcpkg
        .\bootstrap-vcpkg.bat

    - name: Setup vcpkg
      run: |
        C:\vcpkg\vcpkg.exe integrate install
        C:\vcpkg\vcpkg.exe install gtest nlohmann-json openssl

    # - name: Install OpenSSL
    # #   run: powershell.exe ./.github/workflows/Install-OpenSSL.ps1
    #   shell: powershell
    #   run: |
    #     echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
    #     C:\vcpkg\vcpkg.exe install openssl:x64-windows-static-md

    - name: Build tests
      run: |
        cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake .
        cmake --build .

    - name: Run tests
      run: |
        ctest --verbose
